version: '3.1'
services:

  postgres:
    image: postgres:12.12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pmvendor
      - POSTGRES_USER=pmvendor
      - POSTGRES_DB=pmvendor
